version: '3.3'
services:
    run:
        ports:
            - '8080:8080'
            - '5000:5000'
            - '50000:50000'
        volumes:
            - '/home/jenkins:/var/jenkins_home:rw'
            - '/home/michaelkrentz/UnrealEngine:/var/unreal_home:rw'
        image: jenkins/jenkins:lts
