name: Docker Image CI

on:
  push:
    branches: [ "deployment" ]
  pull_request:
    branches: [ "deployment" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - name: Get Cat Studio
      uses: actions/checkout@v3
      
    - name: Clone Unreal 
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
          owner: 'EpicGames'
          repository: 'UnrealEngine'
          access-token: ${{ secrets.DOCKERGITHUBKEY }}
    - name: Build the Docker image 
      run: |
        cd UnrealEngine/ && ./Setup.sh
        cd Engine/Extras/Containers/Dockerfiles/linux/ && ./build.sh 4.26-chaos
    - name: Run Docker File (cats)
      run: |
        cd /f22-kitty-cat-studios/
        docker run --rm -ti -v "." ghcr.io/epicgames/unreal-engine:dev-4.26-chaos



        

