name: BroncoDrome Linter

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch, we can switch this to develop once we set up the git-flow pattern. - Mikey
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    # using super-lint from github
    # Documentation: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
    runs-on: ubuntu-latest

    steps:
      # Checks out our code
      - uses: actions/checkout@v2

      # add the linter
      - name: Super-Linter
        uses: github/super-linter@v4.8.7
        # this should allow access to whole repo
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # this will make it so the linter will only look at the newly commited files, unless the workflow was triggered manually
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'workflow_dispatch' }}
          # lint was throwing spellcheck errors on this file for "run", which is dumb, so we're ignoring changes on this
          VALIDATE_GITHUB_ACTIONS: false
